[package]
name = "http_server_base_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
rusqlite = "0.26.3"
sha2 = "0.10.2"
time = "0.3.7"
